
export const LANGUAGES = {
    RU: 'RU',
    EN: 'EN',
};

export const TRANSLATIONS = {
    [LANGUAGES.EN]:{
        DATE: 'en-En',
        NIGHT: 'Good night,',
        MORNING: 'Good morning,',
        AFTERNOON: 'Good afternoon,',
        EVENING: 'Good evening,',
        WEATHER: 'en',
        HUMIDITY: 'Humidity',
        WIND: 'Wind speed',
        QUOTESJSON: './js/dataEN.json',
        NAME: '[Enter your name]',
        CITYDEFAULT: 'Minsk',
        LANGSETTINGS: 'Languadge:',
        ENSETTINGS: 'English',
        RUSETTINGS: 'Russan',
        BGSETTINGS: 'Chose photo src:',
        OPASITYSETTINGS: 'What you wanna hide:',
        PLAYERSETTINGS: 'Player',
        WEATHERSETTINGS: 'Weater',
        TIMESETTINGS: 'Time',
        DATESETTINGS: 'Date',
        GREETINGSETTINGS: 'Greeting',
        QUOTESETTINGS: 'Quotes',
    },
    [LANGUAGES.RU]:{
        DATE: 'ru-Ru',
        NIGHT: 'Прекрасная ночь,',
        MORNING: 'Доброго утра,',
        AFTERNOON: 'Надеюсь у тебя хороший день,',
        EVENING: 'Славного вечера,',
        WEATHER: 'ru',
        HUMIDITY: 'Влажность',
        WIND: 'Скорость воздуха',
        QUOTESJSON: './js/dataRU.json',
        NAME: '[Введите имя]',
        CITYDEFAULT: 'Минск',
        LANGSETTINGS: 'Язык:',
        ENSETTINGS: 'Английский',
        RUSETTINGS: 'Русский',
        BGSETTINGS: 'Источник фото:',
        OPASITYSETTINGS: 'Скрыть элементы:',
        PLAYERSETTINGS: 'Плеер',
        WEATHERSETTINGS: 'Погода',
        TIMESETTINGS: 'Время',
        DATESETTINGS: 'Дата',
        GREETINGSETTINGS: 'Приветствие',
        QUOTESETTINGS: 'Цитаты',
    },
};